daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
  - frozen
  - is:announcement
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had any activity in the last 60 days.
  It will automatically be closed if no further activity occurs in the next seven days to enable maintainers to
  focus on the most important issues.

  If this issue is still affecting you, please comment below within the next seven days.

  Thank you for your contributions.
closeComment: >
  This issue has been automatically closed because it has not had any recent activity.
