#!/usr/bin/env bash

{
    set -euo pipefail

    VERSION="0.15.2"
    DOWNLOAD_URL=${BATECT_DOWNLOAD_URL:-"https://github.com/charleskorn/batect/releases/download/0.15.2/batect-0.15.2.jar"}

    ROOT_CACHE_DIR=${BATECT_CACHE_DIR:-"$HOME/.batect/cache"}
    CACHE_DIR="$ROOT_CACHE_DIR/$VERSION"
    JAR_PATH="$CACHE_DIR/batect-$VERSION.jar"

    SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"

    function main() {
        if ! haveVersionCachedLocally; then
            download
        fi

        runApplication "$@"
    }

    function haveVersionCachedLocally() {
        [ -f "$JAR_PATH" ]
    }

    function download() {
        checkForCurl

        echo "Downloading batect version $VERSION from $DOWNLOAD_URL..."
        mkdir -p "$CACHE_DIR"
        temp_file=$(mktemp)
        curl -# --fail --show-error --location --output "$temp_file" "$DOWNLOAD_URL"
        mv "$temp_file" "$JAR_PATH"
    }

    function runApplication() {
        checkForJava

        BATECT_WRAPPER_SCRIPT_PATH="$SCRIPT_PATH" \
        HOSTNAME="$HOSTNAME" \
        java -Djava.net.useSystemProxies=true -jar "$JAR_PATH" "$@"
    }

    function checkForCurl() {
        if ! hash curl 2>/dev/null; then
            echo "curl is not installed or not on your PATH. Please install it and try again." >&2
            exit -1
        fi
    }

    function checkForJava() {
        if ! hash java 2>/dev/null; then
            echo "Java is not installed or not on your PATH. Please install it and try again." >&2
            exit -1
        fi

        java_version=$(java -version 2>&1 | head -n1 | sed -n ';s/.* version "\(.*\)\.\(.*\)\..*"/\1.\2/p;')
        java_version_major="${java_version%.*}"
        java_version_minor="${java_version#*.}"

        if (( java_version_major < 1 || ( java_version_major == 1 && java_version_minor <= 7 ) )); then
            echo "The version of Java that is available on your PATH is version $java_version, but version 1.8 or greater is required."
            echo "If you have a newer version of Java installed, please make sure your PATH is set correctly."
            exit -1
        fi
    }

    main "$@"
    exit $?
}
