#! /usr/bin/env bash

set -euo pipefail

echo 'openjdk version "1.8.0_212"' >/dev/stderr
echo 'OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)' >/dev/stderr
echo 'OpenJDK Server VM (build 25.212-b03, mixed mode)' >/dev/stderr
