[versions]
kotlinx-serialization = "1.3.2"
wire = "4.3.0"

[libraries]
bouncycastle = { group = "org.bouncycastle", name = "bcpkix-jdk15on", version = "1.70" }
commons-codec = { group = "commons-codec", name = "commons-codec", version = "1.15" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.21" }
hamkrest-json = { group = "org.araqnid.hamkrest", name = "hamkrest-json", version = "1.1.2" }
hypirion-io = { group = "com.hypirion", name = "io", version = "0.3.1" }
jackson-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version = "2.13.2" }
jimfs = { group = "com.google.jimfs", name = "jimfs", version = "1.2" }
jnr-posix = { group = "com.github.jnr", name = "jnr-posix", version = "3.1.15" }
jnr-unixsocket = { group = "com.github.jnr", name = "jnr-unixsocket", version = "0.38.17" }
jsonschemavalidator = { group = "com.github.java-json-tools", name = "json-schema-validator", version = "2.2.14" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version = "0.43.0" }
kodein = { group = "org.kodein.di", name = "kodein-di", version = "7.11.0" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
osplatformfinder = { group = "org.graylog.repackaged", name = "os-platform-finder", version = "1.2.3" }
wire-grpc-client = { group = "com.squareup.wire", name = "wire-grpc-client", version.ref = "wire" }

[plugins]
wire = { id = "com.squareup.wire", version.ref = "wire" }
